### ISSUE TITLE
Issue with mod_StatPaints since WoT 1.9.1 CT

### ISSUE THREAD

**Issue by CH4MPi** [PolyacovYury/PYmods#10]
2020-05-30 14:23:22.595: ERROR: [EXCEPTION] (scripts/common/items/vehicles.py, 3739):
Traceback (most recent call last):
  File "scripts/common/items/vehicles.py", line 3734, in getItemByCompactDescr
  File "scripts/common/items/__init__.py", line 379, in parseIntCompactDescr
TypeError: unsupported operand type(s) for &: 'CustomPaint' and 'int'

**Comment by PolyacovYury** [comment]
I'm aware that some things are broken in 1.9.1.0. Don't have much time to deal with them, though - https://dueler.club/ takes more than you'd think.  
All I can say is that I got RemodEnabler and Skinner working in hangar, didn't test the battle.  
CamoSelector is properly and thoroughly broken, they refactored A LOT of code that it relies on.  
Will check my mods' battle logic after I get my diploma.

**Comment by CH4MPi** [comment]
Thanks for your feedback. Are you working on the dueler.club project? I did not know that. Hope you still find time for your modifications in all the work. :) Are you currently doing your diploma? Keep up your good modding work

**Comment by PolyacovYury** [comment]
> Are you working on the dueler.club project? I did not know that.
I'm their WoT guy. ;) Will try to ask to put reference to me somewhere not completely hidden.
> Hope you still find time for your modifications in all the work. :)
I hope too. :)
> Are you currently doing your diploma?
Already passed it. Now I'm somehow for some reason a bachelor in applied mathematics. :\
> Keep up your good modding work
Technically, my Dueler Club work is also modding, so - will do :D I'll sure try to squeeze some time for other mods, though I can't promise anything. The most I can do is fix some immediate crashes over the weekend.

**Comment by CH4MPi** [comment]
> I'm their WoT guy. ;) Will try to ask to put reference to me somewhere not completely hidden.
That would be the least

> Already passed it. Now I'm somehow for some reason a bachelor in applied mathematics. :\
Congratulations! 


> Technically, my Dueler Club work is also modding, so - will do :D I'll sure try to squeeze some time for other mods, though I can't promise anything. The most I can do is fix some immediate crashes over the weekend.

In my view it would be a big loss for the WoT modding scene if you stopped developing mods. I learned a lot about WoT modding from the source codes of your and spoter's mods. Maybe you don't know it at all but by revealing your mods you have done a lot for the WoT modding scene.

Is it possible to write to you privately (email or discord etc?)

**Comment by PolyacovYury** [comment]
\*humbled* Thank you! I'm definitely not quitting, more of "my life can become a hectic mess in the near future, but afterwards I can fix stuffs that broke down".

Discord, Polyacov_Yury#7405.

**Comment by CH4MPi** [comment]
Thanks, i will write you there. :)

**Comment by PolyacovYury** [comment]
Just writing here that StatPaints was fixed and uploaded, along with Skinner, RemodEnabler and ShowVehicle.
