### ISSUE TITLE
Request for permission to use your PlayerPanelsAPI in my own mod package

### ISSUE THREAD

**Issue by CH4MPi** [PolyacovYury/PYmods#6]
Hello Yury,

i couldn't find a direct email to get in contact with you, so i will write it here.

I'm a WoT mod developer and want to ask you for permission to include your PlayerPanelsAPI in my mod-package.

Can i use it for my mod too and put the needed PlayerPanelsAPI files in my mod package? Of course you will get the credits for it!

Any feedback would be great.

thanks in advance

**Comment by PolyacovYury** [comment]
Of course you can! Thanks for asking, though.
