### ISSUE TITLE
autogenerated json files

### ISSUE THREAD

**Issue by CH4MPi** [PolyacovYury/PYmods#8]
Hi Yury,

is it possible that there is a small issue with the updated jsonreader/writer suff?
Generated json files, like the mod config files are now missing the space intent in the first line while storing dictionaries.

examples of a mod config file

> **NEW output:**
    "shadow": {
"alpha": 1,  # # 0 spaces - spaces are missing
        "angle": 45, # 4 spaces
        "blurX": 4, # 4 spaces
        "blurY": 4, # 4 spaces
        "distance": 4, # 4 spaces
        "quality": 1, # 4 spaces
        "strength": 1 # 4 spaces
    },

> **OLD output:**
    "shadow": {
        "alpha": 1,  # 4 spaces -  here it is correct
        "angle": 45, # 4 spaces
        "blurX": 4, # 4 spaces 
        "blurY": 4, # 4 spaces
        "distance": 4, # 4 spaces
        "quality": 1, # 4 spaces
        "strength": 1 # 4 spaces
    },

note: GitHub didn't show the blockquote as it should, but i hope you understand the meaning of the issue.

**Comment by PolyacovYury** [comment]
Yep, there was. Cropped up while refactoring some stuff.
Was fixed in https://github.com/PolyacovYury/PYmods/commit/a2eaa90ae3d886d255ef72a37e08dc502c18920a, will merge into master when either 1.8.0.3 or 1.9.0.0 gets released.

**Comment by CH4MPi** [comment]
Thanks, it works now. Keep up your good work and thanks for sharing it!
