### ISSUE TITLE
sorting list of mods in the modsettingsapi by id

### ISSUE THREAD

**Issue by CH4MPi** [PolyacovYury/PYmods#9]
Hi,
this is more a question than an issue. I noticed that the mods listed in the modsettingsapi that you're using in your PYmodsCore have no sorting order. Is it possible to sort them by their (translated) name? This could be helpful when there are a lot of mods.

**Comment by PolyacovYury** [comment]
It would be nice, but sadly, it doesn't depend on me. You'd need to ask the developer of ModsSettingsAPI for that.
